/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.vista;

import dominio.model.dto.Session;
import dominio.model.dto.Usuario;
import javax.swing.JOptionPane;
import ui.controllers.AdminMainController;

/**
 *
 * @author Luca
 */
public class DialogAdminMain extends javax.swing.JDialog implements IAdministradorMainVista{

    private Session session;
    private AdminMainController controlador;
    /**
     * Creates new form AdminMainDialog
     */
    public DialogAdminMain(Session session) {
        this.session = session;
        controlador = new AdminMainController();
        initComponents();
        inicializarValoresComponentes();
    }
    
    private void inicializarValoresComponentes(){
        this.LblUser.setText("Bienvenido, "+session.getUsuario().getNombreCompleto().show());
        this.LblError.setText("");
        mostrarMesas();
        mostrarMontoTotalRecaudado();
        limpiarCampos();
    }
    
    private void limpiarCampos(){
        LblNumeroMano.setText("");
        LblCantidadJugadores.setText("");
        LblTotalApostadoMano.setText("");
        LblEstadoActualMano.setText("");
        LblNombreJugadorGanador.setText("");
        LblNombreFiguraGanador.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblMontoTotalRecaudado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListMesas = new javax.swing.JList<>();
        LblError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrearMesa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JLabel17 = new javax.swing.JLabel();
        LblNumeroMano = new javax.swing.JLabel();
        LblTotalApostadoMano = new javax.swing.JLabel();
        LblCantidadJugadores = new javax.swing.JLabel();
        LblEstadoActualMano = new javax.swing.JLabel();
        LblNombreJugadorGanador = new javax.swing.JLabel();
        LblNombreFiguraGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Administrador de mesas");

        LblUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblUser.setText("Bienvenido, usuario");

        jLabel2.setText("Monto Total Recaudado: ");

        LblMontoTotalRecaudado.setText("$100");

        ListMesas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListMesas);

        LblError.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        LblError.setForeground(new java.awt.Color(255, 0, 51));
        LblError.setText("ERROR");

        jLabel3.setText("Lista Mesas");

        jLabel4.setText("Detalles mesa");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad De Jugadores: ");

        btnCrearMesa.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        btnCrearMesa.setText("Crear Mesa");
        btnCrearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMesaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setText("Numero de Mano: ");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setText("Total Apostado en la Mano: ");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setText("Estado Actual de la Mano: ");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setText("Nombre del Jugador Ganador: ");

        JLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        JLabel17.setText("Nombre de la Figura Ganador: ");

        LblNumeroMano.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblNumeroMano.setText("13");

        LblTotalApostadoMano.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblTotalApostadoMano.setText("13");

        LblCantidadJugadores.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblCantidadJugadores.setText("13");

        LblEstadoActualMano.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblEstadoActualMano.setText("13");

        LblNombreJugadorGanador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblNombreJugadorGanador.setText("13");

        LblNombreFiguraGanador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LblNombreFiguraGanador.setText("13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblMontoTotalRecaudado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 340, Short.MAX_VALUE)
                .addComponent(LblError, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(255, 255, 255)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblCantidadJugadores))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNumeroMano))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTotalApostadoMano))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblEstadoActualMano))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNombreJugadorGanador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNombreFiguraGanador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LblUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LblMontoTotalRecaudado))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LblNumeroMano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LblCantidadJugadores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(LblTotalApostadoMano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(LblEstadoActualMano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(LblNombreJugadorGanador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel17)
                            .addComponent(LblNombreFiguraGanador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(LblError)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMesaActionPerformed
        ejecutarSiguienteCU();
    }//GEN-LAST:event_btnCrearMesaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel17;
    private javax.swing.JLabel LblCantidadJugadores;
    private javax.swing.JLabel LblError;
    private javax.swing.JLabel LblEstadoActualMano;
    private javax.swing.JLabel LblMontoTotalRecaudado;
    private javax.swing.JLabel LblNombreFiguraGanador;
    private javax.swing.JLabel LblNombreJugadorGanador;
    private javax.swing.JLabel LblNumeroMano;
    private javax.swing.JLabel LblTotalApostadoMano;
    private javax.swing.JLabel LblUser;
    private javax.swing.JList<String> ListMesas;
    private javax.swing.JButton btnCrearMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cerrar() {
        controlador.cerrarSesion(session);
    }

    @Override
    public void mostrarMesas() {
        System.out.println("Sin implementar");
    }

    @Override
    public void mostrarMontoTotalRecaudado() {
        String montoTotalRecaudado = Double.toString(controlador.obtnerMontoTotalRecaudado());
        LblMontoTotalRecaudado.setText("$"+montoTotalRecaudado);
    }

    @Override
    public void mostrarError(String error) {
        this.LblError.setText(error);
    }

    @Override
    public void obtenerMesa() {
        System.out.println("Sin implementacion");
    }

    @Override
    public void ejecutarSiguienteCU() {
        new DialogAdminCrearMesa().setVisible(true);
    }


}
