/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.vista;

import dominio.model.dto.Jugador;
import dominio.model.dto.Session;
import ui.controllers.JugadorMainController;

/**
 *
 * @author Luca
 */
public class DialogJugadorMain extends javax.swing.JDialog implements IJugadorMainVista {

    protected Session session;
    protected JugadorMainController controlador;
    private Jugador jugador;
    /**
     * Creates new form JugadorMainDialog
     */
    public DialogJugadorMain(Session session) {
        this.session = session;
        this.controlador = new JugadorMainController(this);
        this.jugador = (Jugador) session.getUsuario();
        initComponents();
        inicializarComponentesInterno();
    }
    
    private void inicializarComponentesInterno(){
        this.LblError.setText("");
        mostrarUsuario();
        mostrarSaldoActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblNombreJugador = new javax.swing.JLabel();
        LblSaldoActual = new javax.swing.JLabel();
        LblError = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("POKER ONLINE");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("SALDO:");

        LblNombreJugador.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LblNombreJugador.setText("Bienvenido, ");

        LblSaldoActual.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LblSaldoActual.setText("$00");

        LblError.setFont(new java.awt.Font("Yu Gothic UI", 2, 12)); // NOI18N
        LblError.setForeground(new java.awt.Color(255, 0, 51));
        LblError.setText("ERROR");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblSaldoActual)
                        .addGap(239, 239, 239)
                        .addComponent(LblError, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(828, Short.MAX_VALUE)
                    .addComponent(LblNombreJugador)
                    .addGap(181, 181, 181)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LblSaldoActual)
                    .addComponent(LblError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(LblNombreJugador)
                    .addContainerGap(451, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblError;
    private javax.swing.JLabel LblNombreJugador;
    private javax.swing.JLabel LblSaldoActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarUsuario() {
        this.LblNombreJugador.setText("Bienvenido, "+session.getUsuario().getNombreCompleto().show());
    }

    @Override
    public void mostrarSaldoActual() {
        this.LblSaldoActual.setText("$"+jugador.getSaldo());
    }

    @Override
    public void mostrarError(String error) {
        this.LblError.setText(error);
    }

    @Override
    public void cerrar() {
        controlador.cerrarSesion(session);
    }

    @Override
    public void mostrarMesasAbiertas() {
        controlador.obtenerMesasAbiertas();
    }
}
