/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.vista;

import dominio.model.dto.Mesa;
import dominio.model.exceptions.MesaException;
import ui.controllers.AdminMesaController;

/**
 *
 * @author Luca
 */
public class DialogAdminCrearMesa extends javax.swing.JDialog implements IAdministradorCrearMesa {

    private AdminMesaController controlador;
    /**
     * Creates new form DialogAdminCrearMesa
     */
    public DialogAdminCrearMesa() {
        controlador = new AdminMesaController(this);
        initComponents();
        inicializarComponentesInterno();
    }
    
    private void inicializarComponentesInterno(){
        LblError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantJugadores = new javax.swing.JTextField();
        btnCrearMesa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMontoApuesta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPorcentajeComision = new javax.swing.JTextField();
        LblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("ALTA MESA");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad de Jugadores");

        txtCantJugadores.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        btnCrearMesa.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnCrearMesa.setText("CREAR");
        btnCrearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMesaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Monto de apuesta base");

        txtMontoApuesta.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Porcentaje de comision");

        txtPorcentajeComision.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        LblError.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        LblError.setForeground(new java.awt.Color(255, 0, 51));
        LblError.setText("ERROR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtCantJugadores)
                            .addComponent(jLabel5)
                            .addComponent(txtMontoApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(txtPorcentajeComision, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(btnCrearMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblError, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPorcentajeComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblError)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMesaActionPerformed
        crearMesa();
    }//GEN-LAST:event_btnCrearMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblError;
    private javax.swing.JButton btnCrearMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCantJugadores;
    private javax.swing.JTextField txtMontoApuesta;
    private javax.swing.JTextField txtPorcentajeComision;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarError(String error) {
        this.LblError.setText(error);
    }

    @Override
    public void crearMesa() {
        try{
            int cantidadJugadores = Integer.parseInt(txtCantJugadores.getText());
            int montoApuesta = Integer.parseInt(txtMontoApuesta.getText());
            int porcentajeComision = Integer.parseInt(txtPorcentajeComision.getText());
            Mesa mesa = new Mesa(cantidadJugadores,montoApuesta,porcentajeComision);
            controlador.crearMesa(mesa);
        }catch(NumberFormatException ne){
            mostrarError("ERROR: Ingresar numeros");
        }catch(MesaException me){
            mostrarError("ERROR: "+me.getMessage());
        }
        
    }

    @Override
    public void cerrar() {
        this.dispose();
    }

}
