/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.vista;

/**
 *
 * @author lpodesta
 */
public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form InicioFrame
     */
    public FrameInicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugadorLogin = new javax.swing.JButton();
        btnAdministradorLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        btnJugadorLogin.setBackground(new java.awt.Color(51, 51, 255));
        btnJugadorLogin.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        btnJugadorLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnJugadorLogin.setText("Jugador");
        btnJugadorLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJugadorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorLoginActionPerformed(evt);
            }
        });

        btnAdministradorLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnAdministradorLogin.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        btnAdministradorLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministradorLogin.setText("Administrador");
        btnAdministradorLogin.setBorder(null);
        btnAdministradorLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministradorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setText("SELECCIONA UNA OPCION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdministradorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJugadorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugadorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministradorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorLoginActionPerformed
        new DialogVistaLoginAdmin().setVisible(true);
    }//GEN-LAST:event_btnAdministradorLoginActionPerformed

    private void btnJugadorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorLoginActionPerformed
        new DialogVistaLoginJugador().setVisible(true);
    }//GEN-LAST:event_btnJugadorLoginActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministradorLogin;
    private javax.swing.JButton btnJugadorLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
